name: dartagram
description: An Instagram public API wrapper with cache.
version: 0.1.2
repository: https://github.com/holy-crusader-py/dartagram

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  faker: ^2.1.0
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
